# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    CountryCheckApi\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/CountryCheck/Shared/Domain/Util/Function/*'

    controllers:
        namespace: CountryCheckApi\
        resource: '../src/*/*/Infrastructure/Adapter/RestAPI/*'
        tags: [ 'controller.service_arguments' ]

    CountryCheckApi\CountryCheck\Shared\Infrastructure\Application\QueryBus\HandlerExecutorMiddleware:
        arguments:
            - '@service_container'
            - '@CountryCheckApi\CountryCheck\Shared\Application\QueryBus\DeclaredQueryCollection'

    CountryCheckApi\CountryCheck\Shared\Application\QueryBus\QueryBus:
        class: CountryCheckApi\CountryCheck\Shared\Infrastructure\Application\QueryBus\QueryBus
        arguments:
            - '@CountryCheckApi\CountryCheck\Shared\Infrastructure\Application\QueryBus\QueryBusCacheMiddleware'
            - '@CountryCheckApi\CountryCheck\Shared\Infrastructure\Application\QueryBus\HandlerExecutorMiddleware'

    CountryCheckApi\CountryCheck\Country\Application\CheckCountry\CheckCountryQueryHandler:
        arguments:
            - '@CountryCheckApi\CountryCheck\Country\Domain\Model\CountryRepository'
            - '@CountryCheckApi\CountryCheck\Country\Domain\Service\CountryCodeFirstLetterIsVocalSpecification'
            - '@CountryCheckApi\CountryCheck\Country\Domain\Service\CountryRegionIsFromEuropeSpecification'
            - '@CountryCheckApi\CountryCheck\Country\Domain\Service\CountryPopulationIsBigEnoughSpecification'
            - '@CountryCheckApi\CountryCheck\Country\Domain\Service\CountryPopulationIsBiggerThanNorwaySpecification'

    CountryCheckApi\CountryCheck\Shared\Infrastructure\Symfony\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
